server:
  port: 8082
spring:
  application:
    name: product
  #Database Config
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/cameltech-product
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        format_sql : true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : update
    show-sql: true
  #Cache config
  cache:
    type:
      redis: simple
    .redis:
      time-to-live: 1000S
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka : true
