server:
  port: 8183

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: product-svc
          uri : lb://PRODUCT-SVC
          predicates:
            - Path=/api/v1/product/**
        - id: order-svc
          uri: lb://ORDER-SVC
          predicates:
            - Path=/api/v1/order/**
        - id: profile-svc
          uri: lb://PROFILE-SVC
          predicates:
            - Path=/api/v1/profile/**


  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:87621/eureka
    fetch-registry: true
    register-with-eureka: true

