eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8085
spring:
    application:
        name: chat-svc
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    kafka:
        consumer:
            group-id: messages
    zipkin:
        base-url: http://localhost:9411
    jwt:
        aws:
            identityPoolUrl: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_C72DqiBn0
            jwkUrl: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_C72DqiBn0/.well-known/jwks.json
            connectionTimeout: 2000
            readTimeout: 2000